services:
    rqs.database.tester:
        class: AppBundle\Service\DatabaseTesterService
        arguments:
            - '@doctrine'

    est.agent:
        class: AppBundle\Service\EstateAgentService
        arguments:
            - '@doctrine'