services:
    rqs.database.tester:
        class: AppBundle\Service\DatabaseTesterService
        arguments:
            - '@doctrine'

    est.agent.phone:
        class: AppBundle\Service\EstateAgentPhoneService
        arguments:
            - '@doctrine'

    est.agent:
        class: AppBundle\Service\EstateAgentService
        arguments:
            - '@doctrine'
            - '@est.agent.phone'