estate_agent_add:
    path:  add.{_format}
    defaults: { _controller: AppBundle:ApiEstateAgent:create }
    methods: [ 'POST' ]

estate_agent_fing_by_phone:
    path:  find/phone.{_format}
    defaults: { _controller: AppBundle:ApiEstateAgent:findPhone }
    methods: [ 'GET' ]

estate_agent_fing_by_url:
    path:  find/url.{_format}
    defaults: { _controller: AppBundle:ApiEstateAgent:findUrl }
    methods: [ 'GET' ]