estate_advertisement_add:
    path:  add.{_format}
    defaults: { _controller: AppBundle:ApiEstateAdvertisement:create }
    methods: [ 'POST' ]

estate_advertisement_fing_by_phone:
    path:  search/phone.{_format}
    defaults: { _controller: AppBundle:ApiEstateAdvertisement:findPhone }
    methods: [ 'GET' ]

estate_advertisement_fing_by_url:
    path:  search/url.{_format}
    defaults: { _controller: AppBundle:ApiEstateAdvertisement:findUrl }
    methods: [ 'GET' ]

estate_advertisement_all_phones:
    path:  phones.{_format}
    defaults: { _controller: AppBundle:ApiEstatePhone:allPhone }
    methods: [ 'GET' ]
